# Generated by Django 3.0.7 on 2020-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default='', upload_to='home/images'),
        ),
    ]
